@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
    Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage {
        + readUserPrefs()
        + saveUserPrefs()
        + getUserPrefsFilePath()
    }
    Class JsonUserPrefsStorage {
        - filePath
        + JsonUserPrefStorage()
        + readUserPrefs()
        + saveUserPrefs()
    }
}

Class "<<interface>>\nStorage" as Storage {
    + readAddressBook()
    + saveAddressBook()
    + readUserPrefs()
    + saveUserPrefs()
    + getAddressBookFilePath()
    + getUserPrefsFilePath()
}

Class StorageManager {
    - userPrefStorage
    - addressBookStorage
    + StorageManager()
    + readAddressBook()
    + saveAddressBook()
    + readUserPrefs()
    + saveUserPrefs()
}

package "AddressBook Storage" #F4F6F6{
    Class "<<interface>>\nAddressBookStorage" as AddressBookStorage {
        + readAddressBook()
        + saveAddressBook()
        + getAddressBookFilePath()
    }

    Class JsonAddressBookStorage {
        - filePath
        + JsonAddressBookStorage()
        + readAddressBook()
        + saveAddressBook()
    }

    Class JsonSerializableAddressBook {
        - persons
        + JsonSerializableAddressBook()
    }

    Class JsonAdaptedPerson {
        - name
        - phone
        - email
    }

    Class JsonAdaptedTag {
        - tagName
    }

    Class JsonAdaptedBooking {
        - id
        - clientName
        - datetime
        - description
    }

}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" AddressBookStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> AddressBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAddressBookStorage .up.|> AddressBookStorage
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonSerializableAddressBook --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag
JsonAdaptedPerson --> "*" JsonAdaptedBooking

@enduml
